#*************************************************************************
# Copyright (c) 2020-2021 ITER Organization.
# This module is distributed subject to a Software License Agreement found
# in file LICENSE that is included with this distribution.
#*************************************************************************

# Author: Ralph Lange <ralph.lange@gmx.de>

# This is a Makefile fragment, see unitTestApp/src/Makefile.

USR_INCLUDES += $(foreach lib, $(_UASDK_MODS),-I$(UASDK)/include/$(lib))

UASDK_OPCUA_OBJS += SessionUaSdk SubscriptionUaSdk ItemUaSdk DataElementUaSdk

#==================================================
# Build tests executables

GTESTPROD_HOST += RangeCheckTest
RangeCheckTest_SRCS += RangeCheckTest.cpp
GTESTS += RangeCheckTest

GTESTPROD_HOST += NamespaceMapTest
NamespaceMapTest_SRCS += NamespaceMapTest.cpp
NamespaceMapTest_LIBS += $(OPCUA_LIBS) $(EPICS_BASE_IOC_LIBS)
NamespaceMapTest_SYS_LIBS_Linux += $(OPCUA_SYS_LIBS_Linux)
NamespaceMapTest_OBJS += $(OPCUA_OBJS)
GTESTS += NamespaceMapTest

# Use RPATH when SDK libs are PROVIDED to find indirect dependencies
ifeq ($(UASDK_DEPLOY_MODE),PROVIDED)
USR_LDFLAGS += -Wl,--no-as-needed
USR_LDFLAGS_Linux += -Wl,--disable-new-dtags
endif
