#*************************************************************************
# Copyright (c) 2020-2021 ITER Organization.
# This module is distributed subject to a Software License Agreement found
# in file LICENSE that is included with this distribution.
#*************************************************************************

# Author: Ralph Lange <ralph.lange@gmx.de>

# This is a Makefile fragment, see unitTestApp/src/Makefile.

USR_INCLUDES += $(foreach lib, $(_UASDK_MODS),-I$(UASDK)/include/$(lib))

UASDK_OPCUA_OBJS += SessionUaSdk SubscriptionUaSdk ItemUaSdk

# Copied from CONFIG_OPCUA - needed here for building the test executables

# Debug builds need the d-marker to be set
# Depending on SDK version, C++ modules may have a 'cpp' suffix
ifeq ($(HOST_OPT),NO)
  D_MARKER = d
endif
_UASDK_MODS = $(notdir $(foreach module, $(UASDK_MODULES), \
$(firstword $(wildcard $(UASDK)/include/$(module)cpp \
$(UASDK)/include/$(module)))))
UASDK_LIBS = $(addsuffix $(D_MARKER), $(_UASDK_MODS))
$(foreach lib, $(UASDK_LIBS), $(eval $(lib)_DIR = $(UASDK_LIB_DIR)))

#==================================================
# Build tests executables

GTESTPROD_HOST += RangeCheckTest
RangeCheckTest_SRCS += RangeCheckTest.cpp
RangeCheckTest_LIBS += $(UASDK_LIBS) $(EPICS_BASE_IOC_LIBS)
GTESTS += RangeCheckTest

GTESTPROD_HOST += NamespaceMapTest
NamespaceMapTest_SRCS += NamespaceMapTest.cpp
NamespaceMapTest_LIBS += $(UASDK_LIBS) $(EPICS_BASE_IOC_LIBS)
NamespaceMapTest_SYS_LIBS_Linux += $(OPCUA_SYS_LIBS_Linux)
NamespaceMapTest_OBJS += $(OPCUA_OBJS)
GTESTS += NamespaceMapTest

# Use RPATH when SDK libs are PROVIDED/EMBED/INSTALL to find indirect dependencies
ifneq ($(UASDK_DEPLOY_MODE),SYSTEM)
USR_LDFLAGS_Linux += -Wl,--no-as-needed
USR_LDFLAGS_Linux += -Wl,--disable-new-dtags
endif
