#*************************************************************************
# Copyright (c) 2023 ITER Organization.
# This module is distributed subject to a Software License Agreement found
# in file LICENSE that is included with this distribution.
#*************************************************************************

# Author: Ralph Lange <ralph.lange@gmx.de>

# This is a Makefile fragment, see unitTestApp/src/Makefile.

USR_INCLUDES += -I$(OPEN62541)/include

OPEN62541_OPCUA_OBJS += SessionOpen62541 SubscriptionOpen62541 ItemOpen62541

# repeated here as the CONFIG_OPEN62541 only does it for PROVIDED
open62541_DIR = $(OPEN62541_LIB_DIR)

#==================================================
# Build tests executables
