#*************************************************************************
# Copyright (c) 2023 ITER Organization.
# This module is distributed subject to a Software License Agreement found
# in file LICENSE that is included with this distribution.
#*************************************************************************

# Author: Ralph Lange <ralph.lange@gmx.de>

# This is a Makefile fragment, see unitTestApp/src/Makefile.

DEVSUP_SRC = $(TOP)/devOpcuaSup
OPEN62541_SRC = $(DEVSUP_SRC)/open62541

SRC_DIRS += $(TESTSRC)/open62541
SRC_DIRS += $(DEVSUP_SRC) $(OPEN62541_SRC)
USR_INCLUDES += -I$(OPEN62541_SRC)
USR_INCLUDES += -I$(OPEN62541)/include

ifeq ($(OPEN62541_USE_CRYPTO),YES)
USR_CXXFLAGS += -DHAS_SECURITY
endif
ifeq ($(OPEN62541_USE_XMLPARSER),YES)
USR_CXXFLAGS += -DHAS_XMLPARSER
USR_INCLUDES_Linux += -I/usr/include/libxml2
endif

#==================================================
# Build tests executables

# Use RPATH when SDK libs are PROVIDED to find indirect dependencies
ifeq ($(UASDK_DEPLOY_MODE),PROVIDED)
USR_LDFLAGS_Linux += -Wl,--disable-new-dtags
endif
