#*************************************************************************
# Copyright (c) 2018-2021 ITER Organization.
# This module is distributed subject to a Software License Agreement found
# in file LICENSE that is included with this distribution.
#*************************************************************************

# Author: Ralph Lange <ralph.lange@gmx.de>
#
# based on prototype work by Bernhard Kuner <bernhard.kuner@helmholtz-berlin.de>
# and code by Michael Davidsaver <mdavidsaver@ospreydcs.com>

#==================================================
# Unified Automation SDK libraries

ifeq ($(UASDK_DEPLOY_MODE),SYSTEM)
USR_SYS_LIBS += $(UASDK_LIBS)
endif

ifeq ($(UASDK_DEPLOY_MODE),PROVIDED)
USR_LIBS += $(UASDK_LIBS)
$(foreach lib, $(UASDK_LIBS), $(eval $(lib)_DIR = $(UASDK_LIB_DIR)))
endif

# EMBED the SDK libraries in libopcua.so
ifeq ($(UASDK_DEPLOY_MODE),EMBED)

# Repeated as in CONFIG_OPCUA because in the EMBED case we do *not*
# want these definitions for users but they are still needed here

# Debug builds need the d-marker to be set
# Depending on SDK version, C++ modules may have a 'cpp' suffix
ifeq ($(HOST_OPT),NO)
D_MARKER = d
endif
_UASDK_MODS = $(notdir $(foreach module, $(UASDK_MODULES), \
$(firstword $(wildcard $(UASDK)/include/$(module)cpp \
$(UASDK)/include/$(module)))))
UASDK_LIBS = $(addsuffix $(D_MARKER), $(_UASDK_MODS))

ifeq ($(LIBRARY_IOC),opcua)
USR_LDFLAGS += -L$(UASDK_LIB_DIR)
SHRLIB_LDLIBS = $(STATIC_LDFLAGS_YES) \
    $(addprefix -l, $(UASDK_LIBS)) \
    $(STATIC_LDLIBS_YES) \
    $(addprefix -l, $($*_LDLIBS) $(LIB_LIBS) $(filter-out $(UASDK_LIBS),$(USR_LIBS)) \
    $($*_SYS_LIBS) $(LIB_SYS_LIBS) $(USR_SYS_LIBS)) \
    $(LDLIBS)
endif

endif # EMBED

# INSTALL the SDK shared libraries in the Device Support module
ifeq ($(UASDK_DEPLOY_MODE),INSTALL)

USR_LIBS += $(UASDK_LIBS)
$(foreach lib, $(UASDK_LIBS), $(eval $(lib)_DIR = $(UASDK_LIB_DIR)))

EXTLIB_INSTALLS += $(addprefix $(INSTALL_SHRLIB)/, \
    $(notdir $(wildcard $(foreach lib, $(UASDK_LIBS), \
    $(UASDK_SHRLIB_DIR)/$(SHRLIB_PREFIX)$(lib)$(SHRLIB_SUFFIX_BASE) ))))

build: $(EXTLIB_INSTALLS)

$(INSTALL_SHRLIB)/$(SHRLIB_PREFIX)%$(SHRLIB_SUFFIX_BASE) : $(UASDK_SHRLIB_DIR)/$(SHRLIB_PREFIX)%$(SHRLIB_SUFFIX_BASE)
	@$(ECHO) "Installing shared library $@ from Unified Automation SDK"
	$(INSTALL) -d -m 555 $< $(@D)
endif # INSTALL
