#*************************************************************************
# Copyright (c) 2020 Paul Scherrer Institut.
# This module is distributed subject to a Software License Agreement found
# in file LICENSE that is included with this distribution.
#*************************************************************************

# Author: Dirk Zimoch <dirk.zimoch@psi.ch>
#
# based on the interface for the Unified Automation OPC UA Client SDK
# by Ralph Lange <ralph.lange@gmx.de>

# This is a Makefile fragment, see devOpcuaSup/Makefile.

#=========================================================
# Implementation using open62541 (https://open62541.org/)

SRC_DIRS += $(OPCUA)/open62541
USR_INCLUDES += -I$(OPCUA)/open62541
USR_DBDFLAGS += -I $(OPCUA)/open62541

ifeq ($(OPEN62541_USE_CRYPTO),YES)
USR_CXXFLAGS += -DHAS_SECURITY
endif
USR_CXXFLAGS += -DHAS_XMLPARSER
ifneq ($(filter -D_MINGW,$(OP_SYS_CPPFLAGS)),)
USR_INCLUDES += -I$(MSYSTEM_PREFIX)/include/libxml2
else
USR_INCLUDES += -I/usr/include/libxml2
endif

opcua_SRCS += Session.cpp
opcua_SRCS += SessionOpen62541.cpp
opcua_SRCS += Subscription.cpp
opcua_SRCS += SubscriptionOpen62541.cpp
opcua_SRCS += ItemOpen62541.cpp
opcua_SRCS += DataElementOpen62541Node.cpp
opcua_SRCS += DataElementOpen62541Leaf.cpp

DBD_INSTALLS += opcua.dbd

CFG += RULES_OPCUA
CFG += CONFIG_OPCUA

EXPAND_VARS += OPEN62541=$(OPEN62541)
EXPAND_VARS += OPEN62541_DEPLOY_MODE=$(OPEN62541_DEPLOY_MODE)
EXPAND_VARS += OPEN62541_LIB_DIR=$(OPEN62541_LIB_DIR)
EXPAND_VARS += OPEN62541_SHRLIB_DIR=$(OPEN62541_SHRLIB_DIR)
EXPAND_VARS += OPEN62541_USE_CRYPTO=$(OPEN62541_USE_CRYPTO)
EXPAND_VARS += OPEN62541_USE_XMLPARSER=$(OPEN62541_USE_XMLPARSER)

USR_INCLUDES += -I$(OPEN62541)/include
