#include <signal.h>
#include <stdlib.h>
#include <stdio.h>
#include <unistd.h>
#include <pthread.h>
#include "open62541.h"
#include "opcuaTestNodeSet.h"

/* Local definitions */
#define SLEEP_TIME_MS 1000
#define MAX_COUNT 1000

/* Structure definition for passing to the
 * thread simulation routine.
 * Server and namespace variables
 */
struct simThreadParams {
    UA_UInt16 *ns;
    UA_Server *server;
};

/* Global variable to enable / disbable the server */
static volatile UA_Boolean running = true;

/* Handler to trigger server stop.
 * Triggered by Ctrl+c.
 */
static void stopHandler(int sig) {
    UA_LOG_INFO(UA_Log_Stdout, UA_LOGCATEGORY_USERLAND, "received ctrl-c");
    running = false;
}
/* Simulation routine. To be launched as a parallel thread */
void *simVariable(void *ptr) {

    struct simThreadParams *threadParams = ptr;
    int utime = SLEEP_TIME_MS * 1000;
    int count = 0;
    UA_Variant value;
    UA_Double cntDouble;
    UA_Server *server = *(&threadParams->server);

    /* While the server is running */
    while(running) {

        /* Increment count */
        if (count >= MAX_COUNT) {
            count = 0;
        } else {
            count++;
        }

        /* Cast value, assign variant, and write to server */
        cntDouble = (UA_Double)count;
        UA_Variant_setScalarCopy(&value, &cntDouble, &UA_TYPES[UA_TYPES_DOUBLE]);
        UA_Server_writeValue(server, UA_NODEID_STRING((*(&threadParams->ns))[1], "Sim.TestRamp"), value);

        /* Sleep the thread */
        usleep(utime);
    }

    UA_LOG_INFO(UA_Log_Stdout, UA_LOGCATEGORY_USERLAND, "Exiting thread");
}

int main(void) {
    signal(SIGINT, stopHandler);
    signal(SIGTERM, stopHandler);

    /* Create new server using default configuration */
    UA_Server *server = UA_Server_new();
    UA_ServerConfig_setDefault(UA_Server_getConfig(server));

    /* Use namespace ids generated by the server */
    UA_UInt16 ns[2];
    ns[0] = UA_Server_addNamespace(server, "http://opcfoundation.org/UA/");
    ns[1] = UA_Server_addNamespace(server, "http://ess.eu/OpcUa");

    /* Add simulation NodeSet */
    UA_StatusCode retval = opcuaTestNodeSet(server);

    pthread_t threadSim;
    int ret = 0;

    /* Create struct to pass to threaded simulation routine
     * Contains server and namespace variables
     */
    struct simThreadParams threadParams;
    threadParams.server = server;
    threadParams.ns = ns;

    /* Create nodes from nodeset */
    if(retval != UA_STATUSCODE_GOOD) {
        UA_LOG_ERROR(UA_Log_Stdout, UA_LOGCATEGORY_SERVER, "Could not add the example nodeset. "
            "Check previous output for any error.");
        retval = UA_STATUSCODE_BADUNEXPECTEDERROR;
    } else {
        ret = pthread_create( &threadSim, NULL, simVariable, &threadParams);
        if(ret) {
            UA_LOG_INFO(UA_Log_Stdout, UA_LOGCATEGORY_USERLAND, "Error - pthread_create(): %d", ret);
            exit(EXIT_FAILURE);
        }
        /* Main server loop. Will remain in this function
         * while running = true
         */
        retval = UA_Server_run(server, &running);
    }

    /* Give thread enough time to exit */
    usleep(SLEEP_TIME_MS * 1000);

    /* Cleanup and return */
    UA_Server_delete(server);
    return retval == UA_STATUSCODE_GOOD ? EXIT_SUCCESS : EXIT_FAILURE;
}
